name: Check version

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:stable
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v2
      with:
        ref: 'version-check'
        path: 'versions'
    - name: version check
      run: ./version-check.sh
    - uses: EndBug/add-and-commit@v7
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        author_name: 'lxylxy123456'
        author_email: 'lixiaoyi13691419520@gmail.com'
        branch: 'version-check'
        cwd: 'versions'
        message: 'Version check update'

