name: Check version

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
    - uses: actions/checkout@v4
    - name: version check
      run: ./version-check.sh

