name: Version check

on:
  push: []
  schedule:
    - cron: '34 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:stable
    steps:
    - name: apt
      run: |
        apt-get update && apt-get install -y git
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        ref: 'version-check'
        path: 'versions'
    - name: version check
      run: ./version-check.sh
    - uses: actions/checkout@v4
      with:
        ref: 'dummy'
        path: 'dummy'
    - name: dummy
      run: |
        cd dummy
        date >> run_dates.txt
        git config user.email "lxylxy123456@github-user"
        git config user.name "lxylxy123456"
        git add -A
        git commit -m 'Dummy commit by version-check.yml'
        git push origin dummy
        cd ..

