name: Version check

on:
  push:
  schedule:
    - cron: '34 12 * * *'

jobs:
  build:
    strategy:
      matrix:
        debian_version: [12, 13]
    runs-on: ubuntu-latest
    container:
      image: debian:${{ matrix.debian_version }}
    steps:
    - name: apt
      run: |
        apt-get update && apt-get install -y git
    - uses: actions/checkout@v5
    - uses: actions/checkout@v5
      with:
        ref: 'version-check'
        path: 'versions'
    - name: version check
      run: |
        cd versions/debian-${{ matrix.debian_version }}
        ../../version-check.sh
    - uses: actions/checkout@v5
      with:
        ref: 'dummy'
        path: 'dummy'
    - name: dummy
      run: |
        cd dummy
        echo "$(date)" >> run_dates_${{ matrix.debian_version }}.txt
        git config user.email "lxylxy123456@github-user"
        git config user.name "lxylxy123456"
        git add -A
        git commit -m 'Dummy commit by version-check.yml'
        git pull origin dummy --no-edit
        git push origin dummy
        cd ..

